[toolchain]

[workspace]
members = ["programs/*"]

[package]
name = "shipyard"
version = "0.1.0"
description = "Proof of Human escrow program"

[programs.localnet]
proof_of_human = "3y31A2BrBSMQ6unaBmXxuT9ZiArsxCkbW1RXf4vmnxX4"

[programs.devnet]
proof_of_human = "3y31A2BrBSMQ6unaBmXxuT9ZiArsxCkbW1RXf4vmnxX4"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"